/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorPrincipal;
import modelo.RegistroAlumno;
import modelo.RegistroCurso;
import modelo.RegistroMatricula;

/**
 *
 * @author tatianacd
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        
        RegistroAlumno registroAlumno = new RegistroAlumno();        
        RegistroCurso registroCurso = new RegistroCurso();
        RegistroMatricula registroMatricula = new RegistroMatricula(registroCurso);
        
        ManejadorPrincipal manejadorPrincipal = new ManejadorPrincipal(registroAlumno,registroCurso, registroMatricula);
        
        jmiAlumno.addActionListener(manejadorPrincipal);
        jmiCurso.addActionListener(manejadorPrincipal);
        jmiMatricula.addActionListener(manejadorPrincipal);
        jmiTodoCursos.addActionListener(manejadorPrincipal);
        jmiVerMatricula.addActionListener(manejadorPrincipal);
        jmiSalir.addActionListener(manejadorPrincipal);
        
        setExtendedState(GUIPrincipal.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmiAlumno = new javax.swing.JMenuItem();
        jmiCurso = new javax.swing.JMenuItem();
        jmiMatricula = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmiTodoCursos = new javax.swing.JMenuItem();
        jmiVerMatricula = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jmAlumno.setText("Archivo");
        jmAlumno.setActionCommand("matricular");

        jmiAlumno.setText("Alumno");
        jmiAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiAlumno);

        jmiCurso.setText("Curso");
        jmiCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCursoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiCurso);

        jmiMatricula.setText("Matricular");
        jmiMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMatriculaActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiMatricula);

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiSalir);

        jMenuBar1.add(jmAlumno);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver");

        jmiTodoCursos.setText("Todos los cursos");
        jMenu3.add(jmiTodoCursos);

        jmiVerMatricula.setText("Ver Matricula");
        jmiVerMatricula.setActionCommand("ver matricula");
        jmiVerMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVerMatriculaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiVerMatricula);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAlumnoActionPerformed

    private void jmiCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCursoActionPerformed

    private void jmiVerMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVerMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiVerMatriculaActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenuItem jmiAlumno;
    private javax.swing.JMenuItem jmiCurso;
    private javax.swing.JMenuItem jmiMatricula;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiTodoCursos;
    private javax.swing.JMenuItem jmiVerMatricula;
    // End of variables declaration//GEN-END:variables
}
